spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
server:
  port: 8191
jwt:
  secret: secretclownstring
  header: Authorization
  expiration: 100500